#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-delorean
Version  : 2.1.0
Release  : 1
URL      : https://rubygems.org/downloads/delorean-2.1.0.gem
Source0  : https://rubygems.org/downloads/delorean-2.1.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-chronic
BuildRequires : rubygem-rdoc

%description
# Delorean [![Build Status](https://secure.travis-ci.org/bebanjo/delorean.png)](http://travis-ci.org/bebanjo/delorean)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n delorean-2.1.0
gem spec %{SOURCE0} -l --ruby > rubygem-delorean.gemspec

%build
gem build rubygem-delorean.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
delorean-2.1.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/delorean-2.1.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Date/cdesc-Date.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Date/today-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Date/today_without_delorean-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/DateTime/cdesc-DateTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/DateTime/now-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/DateTime/now_without_delorean-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/back_to_1985-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/back_to_the_present-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/cdesc-FluxCapacitor.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/jump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/mock_current_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/now-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/restore_previous_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/time_travel_offsets-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/FluxCapacitor/time_travel_to-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Delorean/cdesc-Delorean.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Time/cdesc-Time.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Time/now-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/Time/now_without_delorean-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/delorean-2.1.0/ri/page-README_md.ri
/usr/lib64/ruby/gems/2.2.0/gems/delorean-2.1.0/MIT-LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/delorean-2.1.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/delorean-2.1.0/lib/delorean.rb
/usr/lib64/ruby/gems/2.2.0/gems/delorean-2.1.0/lib/flux_capacitor.rb
/usr/lib64/ruby/gems/2.2.0/specifications/delorean-2.1.0.gemspec
